export default {
  CREATE_TERM_SUCCESS: "CREATE_TERM_SUCCESS",
  UPDATE_TERM_SUCCESS: "UPDATE_TERM_SUCCESS",
  LOAD_TERMS_SUCCESS: "LOAD_TERMS_SUCCESS",

  API_CALL_TRIGGERRED: "API_CALL_TRIGGERRED",
  API_CALL_RETURNED: "API_CALL_RETURNED"
};
