export default {
  LOAD_TERM_CHILDREN_SUCCESS: "LOAD_TERM_CHILDREN_SUCCESS",

  LOAD_TERM_SUCCESS: "LOAD_TERM_SUCCESS",

  API_CALL_TRIGGERRED: "API_CALL_TRIGGERRED",
  API_CALL_RETURNED: "API_CALL_RETURNED"
};
